#==========================================================================
# Description: Build Armbian for Amlogic
# Copyright (C) 2021 https://github.com/lasthinker/amlogic-s9xxx-armbian
#==========================================================================

name: Rebuild Armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      armbian_url:
        description: "Set Armbian Path."
        required: false
        default: ""
      armbian_soc:
        description: "Select Amlogic SoC."
        required: false
        default: "s905x"
        type: choice
        options:
          - all
          - s905x
      armbian_kernel:
        description: "Select Kernel Version."
        required: false
        default: "5.15.75"
        type: choice
        options:
          - 5.4.220_5.10.150
          - 5.10.150_5.15.75
          - 5.15.75_5.4.220
          - 5.15.75
          - 5.10.150
          - 5.4.220
      auto_kernel:
        description: "Auto Use Latest Kernel."
        required: false
        default: true
        type: boolean
      armbian_size:
        description: "Set Armbian ROOTFS Size(Unit: MiB)."
        required: false
        default: "2560"
      armbian_fstype:
        description: "Set Armbian ROOTFS Type."
        required: false
        default: "ext4"
        type: choice
        options:
          - ext4
          - btrfs
      armbian_sign:
        description: "Set Armbian Custom Name."
        required: false
        default: ""

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization Environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc 2>/dev/null
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y $(curl -fsSL https://raw.githubusercontent.com/lasthinker/amlogic-s9xxx-armbian/main/compile-kernel/tools/script/ubuntu2204-build-armbian-depends)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "${TZ}"

          # Get the url of the rebuild armbian file
          armbian_url="${{ github.event.inputs.armbian_url }}"
          if  [[ -z "${armbian_url}" ]]; then
              armbian_site="https://armbian.tnahosting.net/dl/odroidn2/archive/"
              armbian_name="Armbian.*jammy.*.img.xz"
              armbian_file=$(curl -s "${armbian_site}" | grep -oE "${armbian_name}" | head -n 1)
              if [[ -n "${armbian_file}" ]]; then
                  armbian_url="${armbian_site}${armbian_file}"
              else
                  echo -e "Invalid download path: [ ${armbian_site} ]"
                  exit 1
              fi
          fi
          echo "ARMBIAN_URL=${armbian_url}" >> ${GITHUB_ENV}

          # Get the release name of the rebuild armbian file
          set_release="_"
          ARR_RELEASE=("jammy" "focal" "bullseye" "buster" "sid")
          i=1
          for r in ${ARR_RELEASE[*]}; do
              if [[ "${armbian_url}" == *"${r}"* ]]; then
                  set_release="_${r}_"
                  break
              fi
              let i++
          done
          echo "ARMBIAN_RELEASE=${set_release}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Rebuild Armbian for Amlogic S905X
        uses: lasthinker/amlogic-s9xxx-armbian@main
        if: ${{ env.ARMBIAN_URL }} != '' && !cancelled()
        with:
          build_target: armbian
          armbian_path: ${{ env.ARMBIAN_URL }}
          armbian_soc: ${{ github.event.inputs.armbian_soc }}
          armbian_kernel: ${{ github.event.inputs.armbian_kernel }}
          auto_kernel: ${{ github.event.inputs.auto_kernel }}
          armbian_size: ${{ github.event.inputs.armbian_size }}
          armbian_fstype: ${{ github.event.inputs.armbian_fstype }}
          armbian_sign: ${{ github.event.inputs.armbian_sign }}

      - name: Upload Armbian Image to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: armbian_aml${{ env.ARMBIAN_RELEASE }}${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is Armbian Image for Amlogic S905X
            * Firmware Information
            Default Username: root
            Default Password: 1234
            Install Command: armbian-install
            Update Command: armbian-update
