#==========================================================================
# Description: Build Armbian for Amlogic
# Copyright (C) 2021 https://github.com/lasthinker/amlogic-s9xxx-armbian
#==========================================================================

name: Use Releases File to Build Armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_release:
        description: "Select OS Release."
        required: false
        default: "bullseye"
        type: choice
        options:
          - jammy
          - bullseye
      armbian_board:
        description: "Select Box Board."
        required: false
        default: "s905x"
        type: choice
        options:
          - all
          - s905x
      armbian_kernel:
        description: "Select Kernel Version."
        required: false
        default: "5.15.75"
        type: choice
        options:
          - 5.4.220_5.10.150
          - 5.10.150_5.15.75
          - 5.15.75_5.4.220
          - 5.15.75
          - 5.10.150
          - 5.4.220
      auto_kernel:
        description: "Auto Use Latest Kernel."
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "Set Kernel repository."
        required: false
        default: "https://github.com/lasthinker/kernel/tree/main/pub"
      armbian_size:
        description: "Set Armbian ROOTFS Size(Unit: MiB)."
        required: false
        default: "2560"
      armbian_fstype:
        description: "Select Armbian ROOTFS Type."
        required: false
        default: "ext4"
        type: choice
        options:
          - ext4
          - btrfs
      armbian_sign:
        description: "Set Armbian Custom Name."
        required: false
        default: ""

env:
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization Environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/lasthinker/amlogic-s9xxx-armbian/main/compile-kernel/tools/script/ubuntu2204-build-armbian-depends)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Download Armbian from Releases
        id: down
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          armbian_buildpath="build/output/images"
          [[ -d "${armbian_buildpath}" ]] || mkdir -p "${armbian_buildpath}"

          down_filename="$(curl \
                            --header "authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                            -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" |
                            grep -oE "Armbian_${{ inputs.set_release }}.*/Armbian_.*-trunk_.*.img.gz" |
                            head -n 1
                        )"

          [[ -z "${down_filename}" ]] && echo "Invalid download file." && exit 1
          down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"

          wget -q -P "${armbian_buildpath}" "${down_file}" && sync
          cd "${armbian_buildpath}" && gzip -df *.img.gz && sync

          echo "ARMBIAN_RELEASE=${{ inputs.set_release }}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Rebuild Armbian [ ${{ env.ARMBIAN_RELEASE }} ]
        uses: lasthinker/amlogic-s9xxx-armbian@main
        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
        with:
          build_target: armbian
          armbian_path: build/output/images/*.img
          armbian_board: ${{ inputs.armbian_board }}
          armbian_kernel: ${{ inputs.armbian_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          armbian_size: ${{ inputs.armbian_size }}
          armbian_fstype: ${{ inputs.armbian_fstype }}
          armbian_sign: ${{ inputs.armbian_sign }}
          gh_token: ${{ secrets.GH_TOKEN }}

      - name: Upload Armbian Image to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: Armbian_${{ env.ARMBIAN_RELEASE }}_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is Armbian Image for Amlogic S905X
            * Firmware Information
            Default Username: root
            Default Password: 1234
            Install Command: armbian-install
            Update Command: armbian-update
